// Mocks generated by Mockito 5.4.6 from annotations
// in chess/test/features/chess/presentation/bloc/chess_match_bloc/chess_match_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chess/core/utilities/result.dart' as _i4;
import 'package:chess/features/chess/domain/models/game_session.dart' as _i11;
import 'package:chess/features/chess/domain/models/match_result.dart' as _i17;
import 'package:chess/features/chess/domain/models/match_state.dart' as _i18;
import 'package:chess/features/chess/domain/models/opponent.dart' as _i9;
import 'package:chess/features/chess/domain/repository/i_bot_repository.dart'
    as _i12;
import 'package:chess/features/chess/domain/repository/i_session_repository.dart'
    as _i10;
import 'package:chess/features/chess/domain/usecases/get_bot_turn_usecase.dart'
    as _i14;
import 'package:chess/features/chess/domain/usecases/get_opponent_turn_usecase.dart'
    as _i13;
import 'package:chess/features/chess/domain/usecases/get_player_turn_usecase.dart'
    as _i15;
import 'package:chess/features/chess/domain/usecases/get_session_usecase.dart'
    as _i8;
import 'package:chess/features/chess/domain/usecases/make_move_usecase.dart'
    as _i2;
import 'package:chess/features/chess/domain/usecases/match_result_evaluate_usecase.dart'
    as _i16;
import 'package:chess/features/chess/errors/failures.dart' as _i6;
import 'package:dartchess/dartchess.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MakeMoveUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMakeMoveUsecase extends _i1.Mock implements _i2.MakeMoveUsecase {
  @override
  _i3.Future<_i4.Result<_i5.Position, _i6.ChessMoveFailure>> call(
    _i2.MoveParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.Position, _i6.ChessMoveFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.Position, _i6.ChessMoveFailure>
                  >(this, Invocation.method(#call, [params])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i5.Position, _i6.ChessMoveFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.Position, _i6.ChessMoveFailure>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Position, _i6.ChessMoveFailure>>);
}

/// A class which mocks [GetAppUserUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppUserUsecase extends _i1.Mock implements _i8.GetAppUserUsecase {
  @override
  _i3.Future<_i4.Result<_i9.HumanOpponent, _i8.GetAppUserFailure>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i9.HumanOpponent, _i8.GetAppUserFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i9.HumanOpponent, _i8.GetAppUserFailure>
                  >(this, Invocation.method(#call, [params])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i9.HumanOpponent, _i8.GetAppUserFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i9.HumanOpponent, _i8.GetAppUserFailure>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Result<_i9.HumanOpponent, _i8.GetAppUserFailure>>);
}

/// A class which mocks [ISessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionRepository extends _i1.Mock
    implements _i10.ISessionRepository {
  @override
  _i3.Future<Iterable<_i11.GameSession>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<Iterable<_i11.GameSession>>.value(
              <_i11.GameSession>[],
            ),
            returnValueForMissingStub:
                _i3.Future<Iterable<_i11.GameSession>>.value(
                  <_i11.GameSession>[],
                ),
          )
          as _i3.Future<Iterable<_i11.GameSession>>);

  @override
  _i3.Future<_i11.GameSession> getById(_i11.SessionId? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i11.GameSession>.value(
              _i7.dummyValue<_i11.GameSession>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i11.GameSession>.value(
              _i7.dummyValue<_i11.GameSession>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i3.Future<_i11.GameSession>);

  @override
  _i3.Future<_i11.SessionId> create(
    _i11.SessionOpponent? white,
    _i11.SessionOpponent? black,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [white, black]),
            returnValue: _i3.Future<_i11.SessionId>.value(
              _i7.dummyValue<_i11.SessionId>(
                this,
                Invocation.method(#create, [white, black]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i11.SessionId>.value(
              _i7.dummyValue<_i11.SessionId>(
                this,
                Invocation.method(#create, [white, black]),
              ),
            ),
          )
          as _i3.Future<_i11.SessionId>);

  @override
  _i3.Future<void> update(_i11.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#update, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IBotRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBotRepository extends _i1.Mock implements _i12.IBotRepository {
  @override
  _i3.Future<Iterable<_i9.BotOpponent>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<Iterable<_i9.BotOpponent>>.value(
              <_i9.BotOpponent>[],
            ),
            returnValueForMissingStub:
                _i3.Future<Iterable<_i9.BotOpponent>>.value(
                  <_i9.BotOpponent>[],
                ),
          )
          as _i3.Future<Iterable<_i9.BotOpponent>>);

  @override
  _i3.Future<_i9.BotOpponent> getById(_i9.OpponentId? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i9.BotOpponent>.value(
              _i7.dummyValue<_i9.BotOpponent>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i9.BotOpponent>.value(
              _i7.dummyValue<_i9.BotOpponent>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i3.Future<_i9.BotOpponent>);
}

/// A class which mocks [GetOpponentTurnUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOpponentTurnUsecase extends _i1.Mock
    implements _i13.GetOpponentTurnUsecase {
  @override
  _i14.GetBotTurnUsecase get getBotTurnUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getBotTurnUsecase),
            returnValue: _i7.dummyValue<_i14.GetBotTurnUsecase>(
              this,
              Invocation.getter(#getBotTurnUsecase),
            ),
            returnValueForMissingStub: _i7.dummyValue<_i14.GetBotTurnUsecase>(
              this,
              Invocation.getter(#getBotTurnUsecase),
            ),
          )
          as _i14.GetBotTurnUsecase);

  @override
  _i15.GetPlayerTurnUsecase get getPlayerTurnUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getPlayerTurnUsecase),
            returnValue: _i7.dummyValue<_i15.GetPlayerTurnUsecase>(
              this,
              Invocation.getter(#getPlayerTurnUsecase),
            ),
            returnValueForMissingStub: _i7
                .dummyValue<_i15.GetPlayerTurnUsecase>(
                  this,
                  Invocation.getter(#getPlayerTurnUsecase),
                ),
          )
          as _i15.GetPlayerTurnUsecase);

  @override
  _i3.Future<_i4.Result<_i5.Move, _i13.GetOpponentTurnFailure>> call({
    required _i9.Opponent? opponent,
    required _i5.Position? position,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #opponent: opponent,
              #position: position,
            }),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.Move, _i13.GetOpponentTurnFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.Move, _i13.GetOpponentTurnFailure>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #opponent: opponent,
                      #position: position,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i5.Move, _i13.GetOpponentTurnFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i5.Move, _i13.GetOpponentTurnFailure>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #opponent: opponent,
                      #position: position,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Move, _i13.GetOpponentTurnFailure>>);
}

/// A class which mocks [MatchResultEvaluateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchResultEvaluateUseCase extends _i1.Mock
    implements _i16.MatchResultEvaluateUseCase {
  @override
  _i3.Future<_i4.Result<_i17.MatchResult, _i16.MatchResultEvaluateFailure>>
  call(_i18.MatchState? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Result<_i17.MatchResult, _i16.MatchResultEvaluateFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<
                      _i17.MatchResult,
                      _i16.MatchResultEvaluateFailure
                    >
                  >(this, Invocation.method(#call, [params])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Result<_i17.MatchResult, _i16.MatchResultEvaluateFailure>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<
                      _i17.MatchResult,
                      _i16.MatchResultEvaluateFailure
                    >
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<
            _i4.Result<_i17.MatchResult, _i16.MatchResultEvaluateFailure>
          >);
}
