stages:
  - build

build_job:
  stage: build
  image: ghcr.io/cirruslabs/flutter:latest
  scripts:
    - flutter pub get
    - flutter build windows --release
  artifacts:
    paths:
      - build/windows/x64/runner/Release/**/*
    expire_in: 1 week
