// Mocks generated by Mockito 5.4.6 from annotations
// in chess/test/ui/screens/bot_select_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:chess/features/chess/domain/repository/i_bot_repository.dart'
    as _i2;
import 'package:chess/features/chess/domain/usecases/create_match_usecase.dart'
    as _i4;
import 'package:chess/features/chess/domain/usecases/get_session_usecase.dart'
    as _i5;
import 'package:chess/features/chess/domain/usecases/try_find_existing_match_usecase.dart'
    as _i3;
import 'package:chess/features/chess/presentation/bloc/bot_select_bloc/bot_select_bloc.dart'
    as _i7;
import 'package:chess/features/chess/presentation/bloc/bot_select_bloc/events.dart'
    as _i9;
import 'package:chess/features/chess/presentation/bloc/bot_select_bloc/states.dart'
    as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIBotRepository_0 extends _i1.SmartFake
    implements _i2.IBotRepository {
  _FakeIBotRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTryFindExistingMatchUseCase_1 extends _i1.SmartFake
    implements _i3.TryFindExistingMatchUseCase {
  _FakeTryFindExistingMatchUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateMatchUseCase_2 extends _i1.SmartFake
    implements _i4.CreateMatchUseCase {
  _FakeCreateMatchUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAppUserUsecase_3 extends _i1.SmartFake
    implements _i5.GetAppUserUsecase {
  _FakeGetAppUserUsecase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBotSelectBlocState_4 extends _i1.SmartFake
    implements _i6.BotSelectBlocState {
  _FakeBotSelectBlocState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BotSelectBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBotSelectBloc extends _i1.Mock implements _i7.BotSelectBloc {
  @override
  _i2.IBotRepository get botsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#botsRepository),
            returnValue: _FakeIBotRepository_0(
              this,
              Invocation.getter(#botsRepository),
            ),
            returnValueForMissingStub: _FakeIBotRepository_0(
              this,
              Invocation.getter(#botsRepository),
            ),
          )
          as _i2.IBotRepository);

  @override
  _i3.TryFindExistingMatchUseCase get tryFindExistingMatchUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#tryFindExistingMatchUseCase),
            returnValue: _FakeTryFindExistingMatchUseCase_1(
              this,
              Invocation.getter(#tryFindExistingMatchUseCase),
            ),
            returnValueForMissingStub: _FakeTryFindExistingMatchUseCase_1(
              this,
              Invocation.getter(#tryFindExistingMatchUseCase),
            ),
          )
          as _i3.TryFindExistingMatchUseCase);

  @override
  _i4.CreateMatchUseCase get createMatchUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#createMatchUseCase),
            returnValue: _FakeCreateMatchUseCase_2(
              this,
              Invocation.getter(#createMatchUseCase),
            ),
            returnValueForMissingStub: _FakeCreateMatchUseCase_2(
              this,
              Invocation.getter(#createMatchUseCase),
            ),
          )
          as _i4.CreateMatchUseCase);

  @override
  _i5.GetAppUserUsecase get getAppUserUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getAppUserUsecase),
            returnValue: _FakeGetAppUserUsecase_3(
              this,
              Invocation.getter(#getAppUserUsecase),
            ),
            returnValueForMissingStub: _FakeGetAppUserUsecase_3(
              this,
              Invocation.getter(#getAppUserUsecase),
            ),
          )
          as _i5.GetAppUserUsecase);

  @override
  _i6.BotSelectBlocState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBotSelectBlocState_4(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeBotSelectBlocState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.BotSelectBlocState);

  @override
  _i8.Stream<_i6.BotSelectBlocState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.BotSelectBlocState>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i6.BotSelectBlocState>.empty(),
          )
          as _i8.Stream<_i6.BotSelectBlocState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void add(_i9.BotSelectBlocEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.BotSelectBlocEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.BotSelectBlocState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.BotSelectBlocEvent>(
    _i10.EventHandler<E, _i6.BotSelectBlocState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i9.BotSelectBlocEvent, _i6.BotSelectBlocState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i9.BotSelectBlocEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i10.Change<_i6.BotSelectBlocState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
