// Mocks generated by Mockito 5.4.6 from annotations
// in chess/test/features/chess/presentation/bloc/bot_select_bloc/bot_select_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chess/core/utilities/result.dart' as _i9;
import 'package:chess/features/chess/domain/models/game_session.dart' as _i10;
import 'package:chess/features/chess/domain/models/opponent.dart' as _i6;
import 'package:chess/features/chess/domain/repository/i_bot_repository.dart'
    as _i4;
import 'package:chess/features/chess/domain/repository/i_session_repository.dart'
    as _i2;
import 'package:chess/features/chess/domain/usecases/create_match_usecase.dart'
    as _i11;
import 'package:chess/features/chess/domain/usecases/get_session_usecase.dart'
    as _i3;
import 'package:chess/features/chess/domain/usecases/try_find_existing_match_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeISessionRepository_0 extends _i1.SmartFake
    implements _i2.ISessionRepository {
  _FakeISessionRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAppUserUsecase_1 extends _i1.SmartFake
    implements _i3.GetAppUserUsecase {
  _FakeGetAppUserUsecase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IBotRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBotRepository extends _i1.Mock implements _i4.IBotRepository {
  @override
  _i5.Future<Iterable<_i6.BotOpponent>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<Iterable<_i6.BotOpponent>>.value(
              <_i6.BotOpponent>[],
            ),
            returnValueForMissingStub:
                _i5.Future<Iterable<_i6.BotOpponent>>.value(
                  <_i6.BotOpponent>[],
                ),
          )
          as _i5.Future<Iterable<_i6.BotOpponent>>);

  @override
  _i5.Future<_i6.BotOpponent> getById(_i6.OpponentId? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i6.BotOpponent>.value(
              _i7.dummyValue<_i6.BotOpponent>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i6.BotOpponent>.value(
              _i7.dummyValue<_i6.BotOpponent>(
                this,
                Invocation.method(#getById, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.BotOpponent>);
}

/// A class which mocks [TryFindExistingMatchUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTryFindExistingMatchUseCase extends _i1.Mock
    implements _i8.TryFindExistingMatchUseCase {
  @override
  _i2.ISessionRepository get sessionsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#sessionsRepository),
            returnValue: _FakeISessionRepository_0(
              this,
              Invocation.getter(#sessionsRepository),
            ),
            returnValueForMissingStub: _FakeISessionRepository_0(
              this,
              Invocation.getter(#sessionsRepository),
            ),
          )
          as _i2.ISessionRepository);

  @override
  _i3.GetAppUserUsecase get getAppUserUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getAppUserUsecase),
            returnValue: _FakeGetAppUserUsecase_1(
              this,
              Invocation.getter(#getAppUserUsecase),
            ),
            returnValueForMissingStub: _FakeGetAppUserUsecase_1(
              this,
              Invocation.getter(#getAppUserUsecase),
            ),
          )
          as _i3.GetAppUserUsecase);

  @override
  _i5.Future<_i9.Result<_i10.GameSession, _i8.FindExistingMatchFailure>> call(
    _i6.Opponent? opponent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [opponent]),
            returnValue:
                _i5.Future<
                  _i9.Result<_i10.GameSession, _i8.FindExistingMatchFailure>
                >.value(
                  _i7.dummyValue<
                    _i9.Result<_i10.GameSession, _i8.FindExistingMatchFailure>
                  >(this, Invocation.method(#call, [opponent])),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i9.Result<_i10.GameSession, _i8.FindExistingMatchFailure>
                >.value(
                  _i7.dummyValue<
                    _i9.Result<_i10.GameSession, _i8.FindExistingMatchFailure>
                  >(this, Invocation.method(#call, [opponent])),
                ),
          )
          as _i5.Future<
            _i9.Result<_i10.GameSession, _i8.FindExistingMatchFailure>
          >);
}

/// A class which mocks [CreateMatchUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateMatchUseCase extends _i1.Mock
    implements _i11.CreateMatchUseCase {
  @override
  _i2.ISessionRepository get sessionsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#sessionsRepository),
            returnValue: _FakeISessionRepository_0(
              this,
              Invocation.getter(#sessionsRepository),
            ),
            returnValueForMissingStub: _FakeISessionRepository_0(
              this,
              Invocation.getter(#sessionsRepository),
            ),
          )
          as _i2.ISessionRepository);

  @override
  _i5.Future<_i9.Result<_i10.SessionId, _i11.CreateMatchFailure>> call({
    required _i10.SessionOpponent? white,
    required _i10.SessionOpponent? black,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#white: white, #black: black}),
            returnValue:
                _i5.Future<
                  _i9.Result<_i10.SessionId, _i11.CreateMatchFailure>
                >.value(
                  _i7.dummyValue<
                    _i9.Result<_i10.SessionId, _i11.CreateMatchFailure>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #white: white,
                      #black: black,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i9.Result<_i10.SessionId, _i11.CreateMatchFailure>
                >.value(
                  _i7.dummyValue<
                    _i9.Result<_i10.SessionId, _i11.CreateMatchFailure>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #white: white,
                      #black: black,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<_i10.SessionId, _i11.CreateMatchFailure>>);
}

/// A class which mocks [GetAppUserUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppUserUsecase extends _i1.Mock implements _i3.GetAppUserUsecase {
  @override
  _i5.Future<_i9.Result<_i6.HumanOpponent, _i3.GetAppUserFailure>> call(
    _i3.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i9.Result<_i6.HumanOpponent, _i3.GetAppUserFailure>
                >.value(
                  _i7.dummyValue<
                    _i9.Result<_i6.HumanOpponent, _i3.GetAppUserFailure>
                  >(this, Invocation.method(#call, [params])),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i9.Result<_i6.HumanOpponent, _i3.GetAppUserFailure>
                >.value(
                  _i7.dummyValue<
                    _i9.Result<_i6.HumanOpponent, _i3.GetAppUserFailure>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i5.Future<_i9.Result<_i6.HumanOpponent, _i3.GetAppUserFailure>>);
}
